# Generated by Django 4.2.6 on 2023-10-14 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('contact_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('policy_start', models.DateField(default=datetime.date.today)),
                ('life_assured', models.CharField(max_length=30)),
                ('renewal_date', models.DateField()),
                ('payment_frequency', models.DurationField()),
                ('payment_period', models.DurationField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coverage', models.TextField()),
            ],
        ),
    ]
